# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 624)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 809, 561))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(791, 543))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Logout_button = QtWidgets.QPushButton(self.frame)
        self.Logout_button.setGeometry(QtCore.QRect(630, 500, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Logout_button.setFont(font)
        self.Logout_button.setObjectName("Logout_button")
        self.Heading = QtWidgets.QLabel(self.frame)
        self.Heading.setGeometry(QtCore.QRect(10, -10, 741, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.Heading.setFont(font)
        self.Heading.setAlignment(QtCore.Qt.AlignCenter)
        self.Heading.setObjectName("Heading")
        self.CROSettings_button = QtWidgets.QPushButton(self.frame)
        self.CROSettings_button.setGeometry(QtCore.QRect(520, 250, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CROSettings_button.setFont(font)
        self.CROSettings_button.setObjectName("CROSettings_button")
        self.ADMSettings_button = QtWidgets.QPushButton(self.frame)
        self.ADMSettings_button.setGeometry(QtCore.QRect(520, 70, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ADMSettings_button.setFont(font)
        self.ADMSettings_button.setObjectName("ADMSettings_button")
        self.ENGSettings_button = QtWidgets.QPushButton(self.frame)
        self.ENGSettings_button.setGeometry(QtCore.QRect(520, 160, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ENGSettings_button.setFont(font)
        self.ENGSettings_button.setObjectName("ENGSettings_button")
        self.Map_button = QtWidgets.QPushButton(self.frame)
        self.Map_button.setGeometry(QtCore.QRect(0, 160, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Map_button.setFont(font)
        self.Map_button.setObjectName("Map_button")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 500, 171, 41))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.List_button = QtWidgets.QPushButton(self.frame)
        self.List_button.setGeometry(QtCore.QRect(0, 70, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.List_button.setFont(font)
        self.List_button.setObjectName("List_button")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Logout_button.setText(_translate("MainWindow", "Logout"))
        self.Heading.setText(_translate("MainWindow", "Welcome \"User\""))
        self.CROSettings_button.setText(_translate("MainWindow", "Operator Settings"))
        self.ADMSettings_button.setText(_translate("MainWindow", "Admin Settings"))
        self.ENGSettings_button.setText(_translate("MainWindow", "Engineering Settings"))
        self.Map_button.setText(_translate("MainWindow", "View Facility Map"))
        self.label.setText(_translate("MainWindow", "DCS HMI Designed by Scott Taylor. Robert Gordon Univeristy (2023)"))
        self.List_button.setText(_translate("MainWindow", "View Current A&T List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
